/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carfactory.fide;


import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author AMD
 */
public class Nivel1Interfaz extends javax.swing.JFrame {

    //Intento de usar contador y un while para mover listaPedidos
    private int contadorPedidos;

    //Area basurero
    private ZonaBasurero zonaBasurero;

    //Lista de materiales
    private cintaTransportadora cintaTransportadora1 = new cintaTransportadora(10);
    private ZonaConstruccion zonaConstruccion = new ZonaConstruccion();
    private LineaPedidos lineaPedidos = new LineaPedidos();

    //linea Produccion
    private lineaProduccion linea1 = new lineaProduccion();
    private lineaProduccion linea2 = new lineaProduccion();
    private lineaProduccion linea3 = new lineaProduccion();
    //Obtenemos lista de cintraTransportadora 
    ListaMateriales lista = cintaTransportadora1.getMateriales();
    NodoMaterial actual = lista.getcabeza();

    //Obtenemos lista de LineaPedidos
    ListaVehiculos listaVehiculos = lineaPedidos.getLista();
    NodoVehiculo actualVehiculo = listaVehiculos.getCabeza();

    //Hacemos variable global para el drag
    private material materialArrastrar = null;
    private Vehiculo vehiculoArrastrar = null;

    //Vehiculos que estan en las lineas de contruccion
    private Vehiculo vehiculoLinea1 = null;
    private Vehiculo vehiculoLinea2 = null;
    private Vehiculo vehiculoLinea3 = null;

    //Balance 
    private int balance = 0;

    public Nivel1Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        material1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        material2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        material3 = new javax.swing.JLabel();
        basurero = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pedido1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pedido2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pedido3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Produccion1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Produccion2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Produccion3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        ganancias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        material1.setText((actual.getMaterial().getNombre()));
        material1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                material1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(material1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(material1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        material2.setText(actual.siguiente.getMaterial().getNombre());
        material2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                material2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(material2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(material2)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        material3.setText(actual.siguiente.siguiente.getMaterial().getNombre());
        material3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                material3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(material3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(material3)
                .addContainerGap())
        );

        basurero.setBackground(new java.awt.Color(204, 204, 204));
        basurero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                basureroMouseReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carfactory/fide/BasureroPixel.png")));

        javax.swing.GroupLayout basureroLayout = new javax.swing.GroupLayout(basurero);
        basurero.setLayout(basureroLayout);
        basureroLayout.setHorizontalGroup(
            basureroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basureroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basureroLayout.setVerticalGroup(
            basureroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basureroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pedido1.setText(actualVehiculo.getVehiculo().getTipo());
        pedido1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pedido1MouseDragged(evt);
            }
        });
        pedido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pedido1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedido1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pedido1)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pedido2.setText(actualVehiculo.getSiguiente().getVehiculo().getTipo());
        pedido2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pedido2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedido2)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(pedido2)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pedido3.setText(actualVehiculo.getSiguiente().getSiguiente().getVehiculo().getTipo());
        pedido3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pedido3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedido3)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(pedido3)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Produccion1.setText("Linea 1");
        Produccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Produccion1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Produccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Produccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Produccion2.setText("Linea 2");
        Produccion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Produccion2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Produccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Produccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Produccion3.setText("Linea 3");
        Produccion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Produccion3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Produccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Produccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ganancias.setText(String.valueOf(balance));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ganancias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ganancias)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(basurero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basurero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void material1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_material1MousePressed
        if (actual != null) {
            materialArrastrar = actual.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));


    }//GEN-LAST:event_material1MousePressed

    private void material2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_material2MousePressed
        if (actual != null) {
            materialArrastrar = actual.siguiente.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }//GEN-LAST:event_material2MousePressed

    private void material3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_material3MousePressed
        if (actual != null) {
            materialArrastrar = actual.siguiente.siguiente.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }//GEN-LAST:event_material3MousePressed

    private void basureroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basureroMouseReleased
        zonaBasurero = new ZonaBasurero(cintaTransportadora1);
        if (materialArrastrar != null) {
            zonaBasurero.desecharMaterial(materialArrastrar);
            materialArrastrar = null;
            actualizarMateriales();
        }
    }//GEN-LAST:event_basureroMouseReleased

    private void pedido1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedido1MousePressed
        if (actualVehiculo != null) {
            vehiculoArrastrar = actualVehiculo.getVehiculo();

            //seteamos material null solo arrastramos 1
            materialArrastrar = null;
        }
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        //Panels de materiales
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));


    }//GEN-LAST:event_pedido1MousePressed

    private void pedido2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedido2MousePressed
        if (actualVehiculo != null) {
            vehiculoArrastrar = actualVehiculo.getSiguiente().getVehiculo();
            //seteamos material null solo arrastramos 1
            materialArrastrar = null;
        }
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        //Panels de materiales
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pedido2MousePressed

    private void pedido3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedido3MousePressed
        if (actualVehiculo != null) {
            vehiculoArrastrar = actualVehiculo.getSiguiente().getSiguiente().getVehiculo();
            //seteamos material null solo arrastramos 1
            materialArrastrar = null;
        }
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLUE));

        //Panels de materiales
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pedido3MousePressed

    private void Produccion1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produccion1MouseReleased
        if (vehiculoArrastrar != null && materialArrastrar == null) {
            vehiculoLinea1 = vehiculoArrastrar;
            Produccion1.setText(vehiculoLinea1.getTipo());

        } //recibir material
        else if (vehiculoArrastrar == null && materialArrastrar != null) {
            boolean recibido = vehiculoLinea1.recibirMaterial(materialArrastrar);

            if (recibido) {
                if (vehiculoLinea1.estaCompleto()) {
                    Produccion1.setText("Vehiculo completado");
                    ganancias.setText(String.valueOf(balance));
                    vehiculoLinea1 = null;
                    Produccion1.setText("Linea 1");
                } else {
                    Produccion1.setText("Parte recibida - " + vehiculoLinea1.getTipo());
                }
            } else {
                Produccion1.setText("Parte inválida - " + vehiculoLinea1.getTipo());
            }
        }


    }//GEN-LAST:event_Produccion1MouseReleased

    private void Produccion2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produccion2MouseReleased
        if (vehiculoArrastrar != null && materialArrastrar == null) {
            vehiculoLinea2 = vehiculoArrastrar;
            Produccion2.setText(vehiculoLinea2.getTipo());
            System.out.println(vehiculoLinea2.getGanancia());

        } //recibir material
        else if (vehiculoArrastrar == null && materialArrastrar != null) {
            boolean recibido = vehiculoLinea2.recibirMaterial(materialArrastrar);

            if (recibido) {
                if (vehiculoLinea2.estaCompleto()) {
                    Produccion2.setText("Vehiculo completado");
                    balance += vehiculoLinea2.getGanancia();
                    ganancias.setText(String.valueOf(balance));
                    vehiculoLinea2 = null;
                    Produccion2.setText("Linea 2");
                } else {
                    Produccion2.setText("Parte recibida - " + vehiculoLinea2.getTipo());
                }
            } else {
                Produccion2.setText("Parte inválida - " + vehiculoLinea2.getTipo());
            }
        }
    }//GEN-LAST:event_Produccion2MouseReleased

    private void Produccion3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Produccion3MouseReleased
        if (vehiculoArrastrar != null && materialArrastrar == null) {
            vehiculoLinea3 = vehiculoArrastrar;
            Produccion3.setText(vehiculoLinea3.getTipo());

        } //recibir material
        else if (vehiculoArrastrar == null && materialArrastrar != null) {
            boolean recibido = vehiculoLinea3.recibirMaterial(materialArrastrar);

            if (recibido) {
                if (vehiculoLinea3.estaCompleto()) {
                    Produccion3.setText("Vehiculo completado");
                    ganancias.setText(String.valueOf(balance));
                    vehiculoLinea3 = null;
                    Produccion3.setText("Linea 3"); 
                } else {
                    Produccion3.setText("Parte recibida - " + vehiculoLinea3.getTipo());
                }
            } else {
                Produccion3.setText("Parte inválida - " + vehiculoLinea3.getTipo());
            }
        }
    }//GEN-LAST:event_Produccion3MouseReleased

    private void pedido1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedido1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pedido1MouseDragged

    private void actualizarMateriales() {
        actual = lista.getcabeza();

        if (actual != null) {
            material1.setText(actual.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        } else {
            material1.setText("");
        }

        if (actual != null && actual.siguiente != null) {
            material2.setText(actual.siguiente.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        } else {
            material2.setText("");
        }

        if (actual != null && actual.siguiente != null && actual.siguiente.siguiente != null) {
            material3.setText(actual.siguiente.siguiente.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        } else {
            material3.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel1Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel1Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel1Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel1Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel1Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Produccion1;
    private javax.swing.JLabel Produccion2;
    private javax.swing.JLabel Produccion3;
    private javax.swing.JPanel basurero;
    private javax.swing.JLabel ganancias;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel material1;
    private javax.swing.JLabel material2;
    private javax.swing.JLabel material3;
    private javax.swing.JLabel pedido1;
    private javax.swing.JLabel pedido2;
    private javax.swing.JLabel pedido3;
    // End of variables declaration//GEN-END:variables
}
