/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carfactory.fide;

import carfactory.fide.LineaPedidos;
import carfactory.fide.ListaMateriales;
import carfactory.fide.ListaVehiculos;
import carfactory.fide.NodoMaterial;
import carfactory.fide.NodoVehiculo;
import carfactory.fide.Vehiculo;
import carfactory.fide.ZonaBasurero;
import carfactory.fide.ZonaConstruccion;
import carfactory.fide.cintaTransportadora;
import carfactory.fide.lineaProduccion;
import carfactory.fide.material;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author AMD
 */
public class Nivel2Interfaz extends javax.swing.JFrame {

    //Intento de usar contador y un while para mover listaPedidos
    private int contadorPedidos;

    //Area basurero
    private ZonaBasurero zonaBasurero;

    //Lista de materiales
    private cintaTransportadora cintaTransportadora1 = new cintaTransportadora(10);
    private ZonaConstruccion zonaConstruccion = new ZonaConstruccion();
    private LineaPedidos lineaPedidos = new LineaPedidos();

    //linea Produccion
    private lineaProduccion linea1 = new lineaProduccion();
    private lineaProduccion linea2 = new lineaProduccion();
    private lineaProduccion linea3 = new lineaProduccion();
    //Obtenemos lista de cintraTransportadora 
    ListaMateriales lista = cintaTransportadora1.getMateriales();
    NodoMaterial actual = lista.getcabeza();

    //Obtenemos lista de LineaPedidos
    ListaVehiculos listaVehiculos = lineaPedidos.getLista();
    NodoVehiculo actualVehiculo = listaVehiculos.getCabeza();

    //Hacemos variable global para el drag
    private material materialArrastrar = null;
    private Vehiculo vehiculoArrastrar = null;

    //Vehiculos que estan en las lineas de contruccion
    private Vehiculo vehiculoLinea1 = null;
    private Vehiculo vehiculoLinea2 = null;
    private Vehiculo vehiculoLinea3 = null;

    //Balance 
    private int balance = 0;

    public Nivel2Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText((actual.getMaterial().getNombre()));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText(actual.siguiente.getMaterial().getNombre());
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText(actual.siguiente.siguiente.getMaterial().getNombre());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carfactory/fide/BasureroPixel.png")));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText(actualVehiculo.getVehiculo().getTipo());
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText(actualVehiculo.getSiguiente().getVehiculo().getTipo());
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText(actualVehiculo.getSiguiente().getSiguiente().getVehiculo().getTipo());
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Linea 1");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Linea 2");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Linea 3");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText(String.valueOf(balance));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText(actual.siguiente.siguiente.siguiente.getMaterial().getNombre());
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jLabel13.setText("Gerente Regional");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        if (actual != null) {
            materialArrastrar = actual.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));


    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        if (actual != null) {
            materialArrastrar = actual.siguiente.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        if (actual != null) {
            materialArrastrar = actual.siguiente.siguiente.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }//GEN-LAST:event_jLabel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        zonaBasurero = new ZonaBasurero(cintaTransportadora1);
        if (materialArrastrar != null) {
            zonaBasurero.desecharMaterial(materialArrastrar);
            materialArrastrar = null;
            actualizarMateriales();
        }
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        if (actualVehiculo != null) {
            vehiculoArrastrar = actualVehiculo.getVehiculo();

            //seteamos material null solo arrastramos 1
            materialArrastrar = null;
        }
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        //Panels de materiales
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));


    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        if (actualVehiculo != null) {
            vehiculoArrastrar = actualVehiculo.getSiguiente().getVehiculo();
            //seteamos material null solo arrastramos 1
            materialArrastrar = null;
        }
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        //Panels de materiales
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        if (actualVehiculo != null) {
            vehiculoArrastrar = actualVehiculo.getSiguiente().getSiguiente().getVehiculo();
            //seteamos material null solo arrastramos 1
            materialArrastrar = null;
        }
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLUE));

        //Panels de materiales
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        if (vehiculoArrastrar != null && materialArrastrar == null) {
            vehiculoLinea1 = vehiculoArrastrar;
            jLabel8.setText(vehiculoLinea1.getTipo());

        } //recibir material
        else if (vehiculoArrastrar == null && materialArrastrar != null) {
            boolean recibido = vehiculoLinea1.recibirMaterial(materialArrastrar);

            if (recibido) {
                if (vehiculoLinea1.estaCompleto()) {
                    jLabel8.setText("Vehiculo completado");
                    jLabel11.setText(String.valueOf(balance));
                    vehiculoLinea1 = null;
                    jLabel8.setText("Linea 1");
                } else {
                    jLabel8.setText("Parte recibida - " + vehiculoLinea1.getTipo());
                }
            } else {
                jLabel8.setText("Parte inválida - " + vehiculoLinea1.getTipo());
            }
        }


    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        if (vehiculoArrastrar != null && materialArrastrar == null) {
            vehiculoLinea2 = vehiculoArrastrar;
            jLabel9.setText(vehiculoLinea2.getTipo());
            System.out.println(vehiculoLinea2.getGanancia());

        } //recibir material
        else if (vehiculoArrastrar == null && materialArrastrar != null) {
            boolean recibido = vehiculoLinea2.recibirMaterial(materialArrastrar);

            if (recibido) {
                if (vehiculoLinea2.estaCompleto()) {
                    jLabel9.setText("Vehiculo completado");
                    balance += vehiculoLinea2.getGanancia();
                    jLabel11.setText(String.valueOf(balance));
                    vehiculoLinea2 = null;
                    jLabel9.setText("Linea 2");
                } else {
                    jLabel9.setText("Parte recibida - " + vehiculoLinea2.getTipo());
                }
            } else {
                jLabel9.setText("Parte inválida - " + vehiculoLinea2.getTipo());
            }
        }
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        if (vehiculoArrastrar != null && materialArrastrar == null) {
            vehiculoLinea3 = vehiculoArrastrar;
            jLabel10.setText(vehiculoLinea3.getTipo());

        } //recibir material
        else if (vehiculoArrastrar == null && materialArrastrar != null) {
            boolean recibido = vehiculoLinea3.recibirMaterial(materialArrastrar);

            if (recibido) {
                if (vehiculoLinea3.estaCompleto()) {
                    jLabel10.setText("Vehiculo completado");
                    jLabel11.setText(String.valueOf(balance));
                    vehiculoLinea3 = null;
                    jLabel10.setText("Linea 3");
                } else {
                    jLabel10.setText("Parte recibida - " + vehiculoLinea3.getTipo());
                }
            } else {
                jLabel10.setText("Parte inválida - " + vehiculoLinea3.getTipo());
            }
        }
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        if (actual != null) {
            materialArrastrar = actual.getMaterial();
            //Nos aseguramos de arrastrar solo material o solo vehiculo no ambos.
            vehiculoArrastrar = null;
        }
        jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        //Panels de pedidos
        jPanel5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jPanel7.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_jLabel12MousePressed

    private void actualizarMateriales() {
        actual = lista.getcabeza();

        if (actual != null) {
            jLabel1.setText(actual.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        } else {
            jLabel1.setText("");
        }

        if (actual != null && actual.siguiente != null) {
            jLabel2.setText(actual.siguiente.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        } else {
            jLabel2.setText("");
        }

        if (actual != null && actual.siguiente != null && actual.siguiente.siguiente != null) {
            jLabel3.setText(actual.siguiente.siguiente.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        }
        if (actual != null && actual.siguiente != null && actual.siguiente.siguiente != null && actual.siguiente.siguiente.siguiente != null) {
            jLabel12.setText(actual.siguiente.siguiente.siguiente.getMaterial().getNombre());

            //Panels regresan a el borde negro
            jPanel4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            jPanel12.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        } else {
            jLabel3.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel2Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel2Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel2Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel2Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel2Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
